### ISSUE TITLE
Kann man auch ein Scrawler da mit einbinden? Bzw. die Daten auch auf bis 2018 einschränken?

### ISSUE THREAD

**Issue by hh9273664** [Coding-Crashkurse/WM-Tipp-2022-in-Katar#1]

**Comment by Coding-Crashkurse** [comment]
Frag mich sowas lieber auf YouTube ;-). 
Hier: https://github.com/Coding-Crashkurse/WM-Tipp-2022-in-Katar/blob/main/helper.py#L52 findest du den zu ändernden Codepart um die Daten zu filtern :-)
